[custom.all.type-driven-dev-2025]
type = "local"
path = "."
ipkg = "type-driven-dev-2025.ipkg"
test = "test/test.ipkg"

[custom.all.type-driven-dev-2025-test]
type = "local"
path = "test"
ipkg = "test.ipkg"